// Code generated by sqlc. DO NOT EDIT.
// source: like.sql

package db

import (
	"context"
)

const createLike = `-- name: CreateLike :one
INSERT INTO likes (
  user_id, article_id
) VALUES (
  $1, $2
)
RETURNING id, user_id, article_id, created_at, updated_at
`

type CreateLikeParams struct {
	UserID    int32 `json:"user_id"`
	ArticleID int32 `json:"article_id"`
}

func (q *Queries) CreateLike(ctx context.Context, arg CreateLikeParams) (Like, error) {
	row := q.db.QueryRowContext(ctx, createLike, arg.UserID, arg.ArticleID)
	var i Like
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ArticleID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteLike = `-- name: DeleteLike :exec
DELETE FROM likes
WHERE id = $1
`

func (q *Queries) DeleteLike(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteLike, id)
	return err
}

const getLikes = `-- name: GetLikes :many
SELECT id, user_id, article_id, created_at, updated_at FROM likes
WHERE article_id = $1
`

func (q *Queries) GetLikes(ctx context.Context, articleID int32) ([]Like, error) {
	rows, err := q.db.QueryContext(ctx, getLikes, articleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Like{}
	for rows.Next() {
		var i Like
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ArticleID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
