// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Answer struct {
	ID         int64     `json:"id"`
	UserID     int32     `json:"user_id"`
	QuestionID int32     `json:"question_id"`
	Title      string    `json:"title"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Article struct {
	ID                int64     `json:"id"`
	Title             string    `json:"title"`
	Link              string    `json:"link"`
	Image             string    `json:"image"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	ArticleCategoryID int32     `json:"article_category_id"`
	UserID            int32     `json:"user_id"`
}

type ArticleCategory struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Comment struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	UserID    int32     `json:"user_id"`
	AnswerID  int32     `json:"answer_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Like struct {
	ID        int64     `json:"id"`
	UserID    int32     `json:"user_id"`
	ArticleID int32     `json:"article_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Question struct {
	ID                 int64     `json:"id"`
	Title              string    `json:"title"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	UserID             int32     `json:"user_id"`
	QuestionCategoryID int32     `json:"question_category_id"`
}

type QuestionCategory struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Relationship struct {
	ID         int64     `json:"id"`
	FollowerID int32     `json:"follower_id"`
	FollowedID int32     `json:"followed_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Reply struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	ArticleID int32     `json:"article_id"`
	UserID    int32     `json:"user_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Name           string    `json:"name"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	Bio            string    `json:"bio"`
	Birth          time.Time `json:"birth"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Image          string    `json:"image"`
}

type UserArticleRelationship struct {
	ID         int64     `json:"id"`
	FollowerID int32     `json:"follower_id"`
	FollowedID int32     `json:"followed_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type UserQuestionRelation struct {
	ID         int64     `json:"id"`
	FollowerID int32     `json:"follower_id"`
	FollowedID int32     `json:"followed_id"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`
}

type Vote struct {
	ID        int64     `json:"id"`
	UserID    int32     `json:"user_id"`
	AnswerID  int32     `json:"answer_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
