// Code generated by sqlc. DO NOT EDIT.
// source: question_category.sql

package db

import (
	"context"
)

const createQuestionCategory = `-- name: CreateQuestionCategory :one
INSERT INTO question_categories (
  name
) VALUES (
  $1
)
RETURNING id, name, created_at, updated_at
`

type CreateQuestionCategoryParams struct {
	Name  string `json:"name"`
}

func (q *Queries) CreateQuestionCategory(ctx context.Context, arg CreateQuestionCategoryParams) (QuestionCategory, error) {
	row := q.db.QueryRowContext(ctx, createQuestionCategory, arg.Name)
	var i QuestionCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteQuestionCategory = `-- name: DeleteQuestionCategory :exec
DELETE FROM question_categories
WHERE id = $1
`

func (q *Queries) DeleteQuestionCategory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteQuestionCategory, id)
	return err
}

const getQuestionCategory = `-- name: GetQuestionCategory :one
SELECT id, name, created_at, updated_at FROM question_categories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetQuestionCategory(ctx context.Context, id int64) (QuestionCategory, error) {
	row := q.db.QueryRowContext(ctx, getQuestionCategory, id)
	var i QuestionCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listQuestionCategories = `-- name: ListQuestionCategories :many
SELECT id, name, created_at, updated_at FROM question_categories
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListQuestionCategoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListQuestionCategories(ctx context.Context, arg ListQuestionCategoriesParams) ([]QuestionCategory, error) {
	rows, err := q.db.QueryContext(ctx, listQuestionCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuestionCategory
	for rows.Next() {
		var i QuestionCategory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateQuestionCategory = `-- name: UpdateQuestionCategory :one
UPDATE question_categories
SET name = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, name, created_at, updated_at
`

type UpdateQuestionCategoryParams struct {
	Name string `json:"name"`
	ID   int64  `json:"id"`
}

func (q *Queries) UpdateQuestionCategory(ctx context.Context, arg UpdateQuestionCategoryParams) (QuestionCategory, error) {
	row := q.db.QueryRowContext(ctx, updateQuestionCategory, arg.Name, arg.ID)
	var i QuestionCategory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
