// Code generated by sqlc. DO NOT EDIT.
// source: user_question_relation.sql

package db

import (
	"context"
)

const createUserQuestionRelation = `-- name: CreateUserQuestionRelation :one
INSERT INTO user_question_relations (
  follower_id, followed_id
) VALUES (
  $1, $2
)
RETURNING id, follower_id, followed_id, created_at, updated_at
`

type CreateUserQuestionRelationParams struct {
	FollowerID int32 `json:"follower_id"`
	FollowedID int32 `json:"followed_id"`
}

func (q *Queries) CreateUserQuestionRelation(ctx context.Context, arg CreateUserQuestionRelationParams) (UserQuestionRelation, error) {
	row := q.db.QueryRowContext(ctx, createUserQuestionRelation, arg.FollowerID, arg.FollowedID)
	var i UserQuestionRelation
	err := row.Scan(
		&i.ID,
		&i.FollowerID,
		&i.FollowedID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUserQuestionRelation = `-- name: DeleteUserQuestionRelation :exec
DELETE FROM user_question_relations
WHERE follower_id = $1
`

func (q *Queries) DeleteUserQuestionRelation(ctx context.Context, followerID int32) error {
	_, err := q.db.ExecContext(ctx, deleteUserQuestionRelation, followerID)
	return err
}
